### ISSUE TITLE
标定表格记录的灵敏度值未减少1位

### ISSUE THREAD

**Issue by Forcemeasure** [salior/labTester#3]
标定表格记录的灵敏度值未减少1位，应该为5位小数，现在是6位小数。

**Comment by lint019** [comment]
为什么有时候这个板子,打开串口的了以后,发了命令过去受不到任何数据回来?需要重新拔插才行?

**Comment by lint019** [comment]
如已验证此问题，请关闭此问题。 @Forcemeassure

**Comment by Forcemeasure** [comment]
因为用串口供电，有时候会不稳定
