### ISSUE TITLE
保存传感器基本信息时，在win7系统电脑上就不会卡死闪退，但在win10系统会卡死和闪退。

### ISSUE THREAD

**Issue by Forcemeasure** [salior/labTester#4]
保存传感器基本信息时，在win7系统电脑上就不会卡死闪退，但在win10系统会卡死和闪退。

**Comment by lint019** [comment]
请问这个时候,是否打开了"开启检定"?

**Comment by lint019** [comment]
[解决版本，请再次验证](https://github.com/salior/labTester/releases/tag/20200427-2)

**Comment by Forcemeasure** [comment]
已解决
